id = "pinata-theme"
name = "Pinata Theme"
version = "0.0.1"
schema_version = 1
description = "A theme modeled after the Pinata design system"
repository = "https://github.com/stevedylandev/pinata-theme-zed"
authors = ["Steve Simkins <steve@pinata.cloud>"]
themes = ["themes/pinata-theme.json"]
languages = []

[lib]

[grammars]

[language_servers]

[slash_commands]

[indexed_docs_providers]
